guest_list = ["Denis Kolomiets", "Vlad Oborin", "Eugene Kotul", "Pavlo Polishchuk", "Iryna Ponomarenko"]
print("Отправка приглашений")
print(f'{guest_list[0]} - приходи на обед, буду ждать!')
print(f'{guest_list[1]} - приходи на обед, буду ждать!')
print(f'{guest_list[2]} - приходи на обед, буду ждать!')
print(f'{guest_list[3]} - приходи на обед, буду ждать!')
print(f'{guest_list[4]} - приходи на обед, буду ждать!')
print("Приглашения отправлены")

print(f'{guest_list[2]} сказал, что не сможет прийти.')

guest_list[2] = 'Dima Balakhnin'
print("Повторная отправка приглашений")
print(f'{guest_list[0]} - приходи на обед, буду ждать!')
print(f'{guest_list[1]} - приходи на обед, буду ждать!')
print(f'{guest_list[2]} - приходи на обед, буду ждать!')
print(f'{guest_list[3]} - приходи на обед, буду ждать!')
print(f'{guest_list[4]} - приходи на обед, буду ждать!')
print("Приглашения отправлены")

print("Расширение списка гостей")
guest_list.insert(0, "Sasha Pechenkov")
guest_list.insert((len(guest_list) // 2), "Yaroslav Matushevskiy")
guest_list.append("Artem Bratanov")
# print(guest_list)

print("Повторная отправка приглашений")
print(f'{guest_list[0]} - приходи на обед, буду ждать!')
print(f'{guest_list[1]} - приходи на обед, буду ждать!')
print(f'{guest_list[2]} - приходи на обед, буду ждать!')
print(f'{guest_list[3]} - приходи на обед, буду ждать!')
print(f'{guest_list[4]} - приходи на обед, буду ждать!')
print(f'{guest_list[5]} - приходи на обед, буду ждать!')
print(f'{guest_list[6]} - приходи на обед, буду ждать!')
print(f'{guest_list[7]} - приходи на обед, буду ждать!')
print("Приглашения отправлены")