country_list = ["USA", "Japan", "Finland", "South Korea", "Egypt"]
print(country_list)
print(sorted(country_list))
print(country_list)
print(sorted(country_list, reverse=True))
print(country_list)
country_list.reverse()
print(country_list)
country_list.reverse()
print(country_list)
country_list.sort()
print(country_list)
country_list.sort(reverse=True)
print(country_list)
